INFO:root:Model on GPU is True
INFO:root:LSTM Base: hidden_dim: 64, n_epochs: 740, batch_size: 1024.
INFO:root:Trace path: data/flipped/1556.csv
INFO:root:Prediction window = 100.0 ms
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/UserPrediction6DOF/__main__.py", line 45, in <module>
    APPLICATION.run()
  File "/opt/UserPrediction6DOF/application.py", line 91, in run
    self.run_lstm()
  File "/opt/UserPrediction6DOF/application.py", line 140, in run_lstm
    runner.run()
  File "/opt/UserPrediction6DOF/runners.py", line 372, in run
    opt = LSTMOptimization(model=self.model, loss_fn=loss_fn, optimizer=optimizer)
  File "/opt/UserPrediction6DOF/lstm.py", line 256, in __init__
    self.model.cuda()
TypeError: 'bool' object is not callable
-------------------------------------------------------------------------
-------------------------------------------------------------------------
X_train (71999, 11), X_val (24000, 11), X_test(24000, 11), y_train (71999, 7), y_val (24000, 7), y_test (24000, 7)
